version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 127.0.0.1:8080:80
    environment:
      - PMA_ARBITRARY=1
